help:
	@echo "Usage:"
	@echo "	make install:	install project"
	@echo "	make run:	run project"

install:
	@pip3 install prettytable --user
	@pip3 install glpk --user
	@pip3 install pylab-sdk --user
	@pip3 install numpy --user
	@pip3 install matplotlib --user
	@pip3 install progress --user

run:
	@python3 Main.py

