help:
	@echo "Usage:"
	@echo "	make install:	install project"
	@echo "	make run:	run project"

install:
	@pip install prettytable --user
	@pip install glpk --user
	@pip install pylab-sdk --user
	@pip install numpy --user
	@pip install matplotlib --user
	@pip install progress --user

run:
	@python Main.py

